version: "3.7"
services:
  my-postgres:
    image: "postgres"
    restart: always
    ports:
      - "5431:5432"
    command:
      ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: server_db
  adminer:
    image: adminer
    restart: always
    ports:
      - 9000:8080
  my-redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
